export enum OrderStatus {
    PENDING="PENDING",
    ACCEPTED="ACCEPTED",
    PENDING_PAYMENT="PENDING_PAYMENT",
    PAID="PAID",
    SHIPPING="SHIPPING",
    COMPLETED="COMPLETED",
    REFUND="REFUND",
    CANCELLED="CANCELLED",
    REJECT="REJECT"
}