server:
  port: 8087
spring:
  application:
    name: storefront-bff
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity.local/realms/Identity
        registration:
          keycloak:
            provider: keycloak
            client-id: storefront-bff
            client-secret: 9g8Hyka2XXIOU6rKlMLqbZnMcroxhbx2
            scope: openid, profile, email, roles
---
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: api_product_local
          uri: http://nginx
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - StripPrefix=1
        - id: nextJs
          uri: http://host.docker.internal:3000
          predicates:
            - Path=/**
      default-filters:
        - SaveSession
---
services:
  token-identity: http://identity.local/realms/Identity/protocol/openid-connect/token
  cart: http://api.local/cart
  customer: http://api.local/customer
