server:
  port: 8087
spring:
  application:
    name: storefront-bff
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity.local/realms/Identity
        registration:
          keycloak:
            provider: keycloak
            client-id: storefront-bff
            client-secret: O4ZjxsbPLl1c7RxiUO26Y4BzBztGeV1F
            scope: openid, profile, email, roles
---
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.server: DEBUG
---
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: api_product_local
          uri: http://nginx
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - StripPrefix=1
#        - id: nextJs
#          uri: http://host.docker.internal:3000
#          predicates:
#            - Path=/**
      default-filters:
        - SaveSession
---
services:
  token-identity: http://identity.local/realms/Identity/protocol/openid-connect/token
  cart: http://api.local/cart
  customer: http://api.local/customer
